name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: ankane/pgvector:v0.5.0
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_company_db
        options: >-
          --health-cmd="pg_isready -U user -d test_company_db"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5

      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Wait for PostgreSQL and Redis services to be ready
      - name: Wait for PostgreSQL and Redis to be ready
        run: |
          for i in {1..10}; do
            nc -z localhost 5432 && nc -z localhost 6379 && break || sleep 5;
          done

      # Step 5: Run tests with pytest
      - name: Run tests
        run: |
          pytest tests/ --maxfail=5 --disable-warnings -v
